### ISSUE TITLE
Make it a ROS package

### ISSUE THREAD

**Issue by awesomebytes** [dheera/rosshow#1]
Instead of a standalone-manually-installable package, why not make it a ROS package?

It is a very useful tool I think! I can help on that and releasing it if you want.

**Comment by dheera** [comment]
Working on this -- if you have progress let me know, if not I will probably be able to do this within a few days.

**Comment by dheera** [comment]
Hi @awesomebytes Sorry it has been so long! I'm working a bit more actively on this now.

**Comment by dheera** [comment]
It is now a ROS package and Python 2.x compatible.
