### ISSUE TITLE
nav_msgs/OccupancyGrid

### ISSUE THREAD

**Issue by gbr1** [dheera/rosshow#13]
Hi @dheera, your work is just awesome!

Can you add this message? [http://docs.ros.org/melodic/api/nav_msgs/html/msg/OccupancyGrid.html](http://docs.ros.org/melodic/api/nav_msgs/html/msg/OccupancyGrid.html)

It could be useful to show costmap or gridmap during slam!

Thank you!!!

**Comment by dheera** [comment]
on the todo list!

**Comment by gbr1** [comment]
@dheera AWESOME!

**Comment by salihmarangoz** [comment]
I tried drawing map in my forked repository. But it's resolution is very low. I found another project. This project can draw images with higher resolution:
https://github.com/stefanhaustein/TerminalImageViewer

![screenshot_tiv](https://user-images.githubusercontent.com/12991962/60246146-cb1af980-98c6-11e9-893f-68c7833eaf9f.png)
![original_image](https://user-images.githubusercontent.com/12991962/60246147-cb1af980-98c6-11e9-9443-24539c86ccf6.jpg)

**Comment by gbr1** [comment]
@salihmarangoz thanks for your suggestion!
I am going to try it next weekend!

I'm looking something of lighter than rviz due low bandwidth during faires.

**Comment by salihmarangoz** [comment]
For low bandwidth issues you should use compressed topics for communication . See here: https://github.com/tu-darmstadt-ros-pkg/topic_proxy

**Comment by dheera** [comment]
@salihmarangoz @gbr1 
Sorry for the extremely overdue response on this but there is now preliminary support for nav_msgs/OccupancyGrid

I'll consider adding zoom in/out support as well later.
