### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by beduffy** [dheera/rosshow#24]
This package looks awesome, trying to get it working. The instructions were not as clear as I'd like for installation. I had the package.xml issue first so I realised I should copy the xml like this? 
`cp package.ros1.xml package.xml`
and then I first I ran `./ros-install-this`
and got this error:
```
-- +++ processing catkin package: 'rosshow'
-- ==> add_subdirectory(rosshow)
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkin_workspace.cmake:121 (add_subdirectory):
  The source directory

    /tmp/ros-install-this.ilUctk/src/rosshow

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)
```

what are the exact steps I should run to install this package?

**Comment by dheera** [comment]
Hi,
You also need to copy CMakeLists.ros1.xml to CMakeLists.txt. There is a "configure-ros1" script that does this for you.
I should update the README soon -- sorry about the glitch as I've been overhauling this repo for ros1/ros2 support and forgot to update the docs. Thanks!

**Comment by beduffy** [comment]
Thank you so much, it works now. I'm happy you updated the README and the output looks great. I will update the code as well.
