### ISSUE TITLE
Error: ROS time moved backwards

### ISSUE THREAD

**Issue by salihmarangoz** [dheera/rosshow#8]
I have received this error:
[ERROR] [1554129332.456079]: ROS time moved backwards: 196.454957049s

I think rate.sleep() in main causes this error. This sleep function must be independent from ROS time. Because if I set **use_sim_time** to "true" and then publish **/clock** with 1/10 speed of world clock I would get 1.5 FPS. This would be a problem for rosbag and gazebo users.

You can use system's sleep() function here. Also max_fps would be an optional parameter to execute rosshow. 

Sorry for not creating a pull request. I will try to do in this week if I can.

**Comment by dheera** [comment]
Thanks @salihmarangoz . The problem with the system sleep() function is that it only defines the delay between frames, while rospy.Rate.sleep accounts for the loop's processing time to maintain a particular loop frequency.

There are 2 solutions, I guess -- one is to write rospy.Rate using the system sleep(), but perhaps more clean would be to just catch this exception and keep going. Will look into this later.

**Comment by dheera** [comment]
@salihmarangoz I have resolved the issue in the latest commit by catching the exception and continuing on with the loop. Please re-open the issue if it does not work for you.

**Comment by salihmarangoz** [comment]
9e62825f6c53a9591f083c7959f5819e8e00ddb5 solves exception problem. But it will not solve the ROS clock problem. To create the problem; play 100hz data using rosbag with 0.1 rate then use rosshow. As a result data will arrive at 10hz but rosshow will run at 1.5 fps. To solve this problem prefer using system's sleep function. I will pr if I can.

**Comment by salihmarangoz** [comment]
> Thanks @salihmarangoz -- I'm guessing you get this when you run rosbags on loop.
> 
> The problem with the system sleep() function is that it only defines the delay between frames, while rospy.Rate.sleep accounts for the while loop's processing time to maintain the given frequency.
> 
> There are 2 solutions, I guess -- one is to write a version of rospy.Rate using the system sleep(), but perhaps more clean and proper would be to just catch ROSTimeMovedBackwardsException and keep going. Will look into this later.

There two types of clocks in ROS: wall clock and ros time. Ros time speed can be changed due to simulation clock. There is no implementation of Wall Clock in rospy. So time.sleep() can be used here. Rosshow has to catch a specific frame rate in real world time.

For writing the code similar to wallclock ros rate; it's source code can be useful: https://docs.ros.org/api/rospy/html/rospy.timer-pysrc.html#Rate.sleep
